ui-kit is ready
Starrkkiller/lessons-js-core pull request #1
Opened 2022-08-14 11:22 UTC by Starrkkiller

2022-08-18 16:56 UTC, Starrkkiller commented
https://starrkkiller.github.io/lessons-js-core/

2022-08-24 00:28 UTC, Muslik requested changes
Несоответствие с макетом

2022-08-27 22:36 UTC, Muslik requested changes
Замечания будут в видео

2022-09-04 13:05 UTC, Muslik approved these changes
Исправьте замечание.

2022-09-04 13:05 UTC, Muslik commented on index.html
> +          <button href="#" class="button button__theme_position">
У кнопки не может быть href

2022-09-04 13:05 UTC, Muslik commented on index.html
> +          <button href="#" class="button button__theme_position button__theme_colored">
Если вам нужно сделать отступ, то не нужно трогать модификаторы. Вы двум кнопка задаете классы и далее:
```css
.delete-choice__button {
  margin-bottom: 0.5rem;
  }
  .delete-choice__button:last-child {
  margin-bottom: 0;
  }
 ```
 Вы задает кнопке класс элемента конкретного блока. И в рамках именно этого блока у нее будет отступ.

2022-09-04 16:05 UTC, merged